In [1]:
# ------------------------------
# 04_SQLite_Database_Creation.ipynb
# PROJECT: Placement Eligibility Streamlit Application
# PURPOSE: Create SQLite DB, Tables, and Populate with Faker Data
# ------------------------------

import sqlite3
from faker import Faker
import random
import pandas as pd
import datetime

# Suppress warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# ------------------------------
# 1️⃣ Create SQLite Connection
# ------------------------------
conn = sqlite3.connect("placement_eligibility.db")
cursor = conn.cursor()
print("✅ SQLite Database Connected")

✅ SQLite Database Connected

In [3]:
# ------------------------------
# 2️⃣ Create Students Table
# ------------------------------
cursor.execute("""
CREATE TABLE IF NOT EXISTS Students (
    student_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    gender TEXT,
    email TEXT UNIQUE,
    phone TEXT,
    enrollment_year INTEGER,
    course_batch TEXT,
    city TEXT,
    graduation_year INTEGER
)
""")
print("✅ Students Table Created")

# ------------------------------
# 3️⃣ Create Programming Table
# ------------------------------
cursor.execute("""
CREATE TABLE IF NOT EXISTS Programming (
    programming_id INTEGER PRIMARY KEY,
    student_id INTEGER,
    language TEXT,
    problems_solved INTEGER,
    assessments_completed INTEGER,
    mini_projects INTEGER,
    certifications_earned INTEGER,
    latest_project_score REAL,
    FOREIGN KEY(student_id) REFERENCES Students(student_id)
)
""")
print("✅ Programming Table Created")

# ------------------------------
# 4️⃣ Create Soft Skills Table
# ------------------------------
cursor.execute("""
CREATE TABLE IF NOT EXISTS SoftSkills (
    soft_skill_id INTEGER PRIMARY KEY,
    student_id INTEGER,
    communication INTEGER,
    teamwork INTEGER,
    presentation INTEGER,
    leadership INTEGER,
    critical_thinking INTEGER,
    interpersonal_skills INTEGER,
    FOREIGN KEY(student_id) REFERENCES Students(student_id)
)
""")
print("✅ Soft Skills Table Created")

# ------------------------------
# 5️⃣ Create Placements Table
# ------------------------------
cursor.execute("""
CREATE TABLE IF NOT EXISTS Placements (
    placement_id INTEGER PRIMARY KEY,
    student_id INTEGER,
    mock_interview_score INTEGER,
    internships_completed INTEGER,
    placement_status TEXT,
    company_name TEXT,
    placement_package REAL,
    interview_rounds_cleared INTEGER,
    placement_date TEXT,
    FOREIGN KEY(student_id) REFERENCES Students(student_id)
)
""")
print("✅ Placements Table Created")

# Commit table creation
conn.commit()

✅ Students Table Created
✅ Programming Table Created
✅ Soft Skills Table Created
✅ Placements Table Created

In [4]:
# ------------------------------
# 6️⃣ Initialize Faker
# ------------------------------
fake = Faker()
Faker.seed(42)
random.seed(42)

# Number of students
num_students = 20

In [12]:
# Generate Students Data

students_data = []
for i in range(1, num_students+1):
    name = fake.name()
    age = random.randint(20, 28)
    gender = random.choice(["Male", "Female", "Other"])
    email = fake.unique.email()
    phone = fake.phone_number()
    enrollment_year = random.randint(2019, 2023)
    course_batch = f"DS Batch {random.randint(1,5)}"
    city = fake.city()
    graduation_year = enrollment_year + 4
    students_data.append((i, name, age, gender, email, phone, enrollment_year, course_batch, city, graduation_year))

df_students = pd.DataFrame(students_data, columns=[
    "student_id","name","age","gender","email","phone",
    "enrollment_year","course_batch","city","graduation_year"
])

df_students.head()

,student_id,name,age,gender,email,phone,enrollment_year,course_batch,city,graduation_year
0,1,Matthew Hoover,27,Female,tylerjohnson@example.net,001-851-471-8702,2021,DS Batch 2,South Kimberlyview,2025
1,2,Michael Santos,23,Male,melissa86@example.com,+1-978-409-1343x1611,2020,DS Batch 4,Rebeccaton,2024
2,3,Anthony Howard,25,Female,hthomas@example.com,001-922-421-9693,2019,DS Batch 3,South Dana,2023
3,4,Michael Nolan,25,Other,rsantana@example.net,(617)559-4647,2023,DS Batch 4,Castanedaville,2027
4,5,Kenneth Andrews,28,Female,andrew64@example.org,001-509-674-3953,2019,DS Batch 1,Lake Colton,2023

In [13]:
# Generate programming Data

programming_data = []

languages = ["Python", "SQL", "R", "Java"]

for student in df_students['student_id']:
    language = random.choice(languages)
    problems_solved = random.randint(10, 100)
    assessments_completed = random.randint(1, 10)
    mini_projects = random.randint(0, 5)
    certifications_earned = random.randint(0, 3)
    latest_project_score = round(random.uniform(60, 100), 2)
    programming_data.append((None, student, language, problems_solved, assessments_completed, mini_projects, certifications_earned, latest_project_score))

df_programming = pd.DataFrame(programming_data, columns=[
    "programming_id","student_id","language","problems_solved",
    "assessments_completed","mini_projects","certifications_earned","latest_project_score"
])

df_programming.head()

,programming_id,student_id,language,problems_solved,assessments_completed,mini_projects,certifications_earned,latest_project_score
0,None,1,SQL,75,8,5,1,86.35
1,None,2,R,75,10,2,0,92.74
2,None,3,SQL,96,5,1,1,65.89
3,None,4,Python,41,8,4,0,78.22
4,None,5,SQL,99,7,3,3,69.76

In [15]:
# Generate Soft Skills Data

softskills_data = []

for student in df_students['student_id']:
    communication = random.randint(50, 100)
    teamwork = random.randint(50, 100)
    presentation = random.randint(50, 100)
    leadership = random.randint(50, 100)
    critical_thinking = random.randint(50, 100)
    interpersonal_skills = random.randint(50, 100)

    softskills_data.append((
        None, student, communication, teamwork, presentation,
        leadership, critical_thinking, interpersonal_skills
    ))

df_softskills = pd.DataFrame(softskills_data, columns=[
    "soft_skill_id","student_id","communication","teamwork",
    "presentation","leadership","critical_thinking","interpersonal_skills"
])

df_softskills.head()

,soft_skill_id,student_id,communication,teamwork,presentation,leadership,critical_thinking,interpersonal_skills
0,None,1,98,79,86,89,92,74
1,None,2,71,51,81,70,61,81
2,None,3,63,72,66,71,67,88
3,None,4,94,67,85,50,83,62
4,None,5,55,65,96,76,81,85

In [16]:
#  Generate Placement Data

placement_data = []

for student in df_students['student_id']:
    mock_interview_score = random.randint(50, 100)
    internships_completed = random.randint(0, 3)
    placement_status = random.choice(["Ready", "Not Ready", "Placed"])

    if placement_status == "Placed":
        company_name = fake.company()
        placement_package = round(random.uniform(3.0, 15.0), 2)  # Lakhs per annum example
        interview_rounds_cleared = random.randint(1, 5)
        placement_date = fake.date_between(start_date="-1y", end_date="today")
    else:
        company_name = None
        placement_package = None
        interview_rounds_cleared = 0
        placement_date = None

    placement_data.append((
        None, student, mock_interview_score, internships_completed,
        placement_status, company_name, placement_package,
        interview_rounds_cleared, placement_date
    ))

df_placements = pd.DataFrame(placement_data, columns=[
    "placement_id","student_id","mock_interview_score","internships_completed",
    "placement_status","company_name","placement_package",
    "interview_rounds_cleared","placement_date"
])

df_placements.head()

,placement_id,student_id,mock_interview_score,internships_completed,placement_status,company_name,placement_package,interview_rounds_cleared,placement_date
0,None,1,54,3,Not Ready,None,NaN,0,None
1,None,2,54,0,Ready,None,NaN,0,None
2,None,3,59,2,Ready,None,NaN,0,None
3,None,4,65,0,Placed,Webster-Wolf,12.17,5,2025-05-28
4,None,5,88,1,Placed,"Glass, Cunningham and Reid",7.56,4,2025-08-04

In [19]:
df_students.to_sql("Students", conn, if_exists="replace", index=False)
df_programming.to_sql("Programming", conn, if_exists="replace", index=False)
df_softskills.to_sql("SoftSkills", conn, if_exists="replace", index=False)
df_placements.to_sql("Placements", conn, if_exists="replace", index=False)

conn.commit()
print("🔄 Tables replaced and data saved!")

🔄 Tables replaced and data saved!

In [20]:
result = pd.read_sql_query("""
SELECT s.student_id, s.name, p.placement_status, p.company_name
FROM Students s
LEFT JOIN Placements p ON s.student_id = p.student_id
LIMIT 10
""", conn)

result

   student_id             name placement_status                company_name
0           1   Matthew Hoover        Not Ready                        None
1           2   Michael Santos            Ready                        None
2           3   Anthony Howard            Ready                        None
3           4    Michael Nolan           Placed                Webster-Wolf
4           5  Kenneth Andrews           Placed  Glass, Cunningham and Reid
5           6    Amanda Kramer        Not Ready                        None
6           7      Brenda Levy           Placed                  Lin-Burton
7           8  Kristina Herman           Placed                 Jones-Ramos
8           9    Patrick Moore            Ready                        None
9          10       Anna Lewis            Ready                        None

In [32]:
# ------------------------------
# Merge all tables
# ------------------------------


# Merge Students + Programming
df_merged = pd.merge(df_students, df_programming, on="student_id", how="left")

# Merge with SoftSkills
df_merged = pd.merge(df_merged, df_softskills, on="student_id", how="left")

# Merge with Placements
df_merged = pd.merge(df_merged, df_placements, on="student_id", how="left")

# Check the merged dataset
print("Number of rows:", len(df_merged))
print("Columns in merged dataset:", df_merged.columns)
df_merged.head()

Number of rows: 20
Columns in merged dataset: Index(['student_id', 'name', 'age', 'gender', 'email', 'phone',
       'enrollment_year', 'course_batch', 'city', 'graduation_year',
       'programming_id', 'language', 'problems_solved',
       'assessments_completed', 'mini_projects', 'certifications_earned',
       'latest_project_score', 'soft_skill_id', 'communication', 'teamwork',
       'presentation', 'leadership', 'critical_thinking',
       'interpersonal_skills', 'placement_id', 'mock_interview_score',
       'internships_completed', 'placement_status', 'company_name',
       'placement_package', 'interview_rounds_cleared', 'placement_date'],
      dtype='object')

,student_id,name,age,gender,email,phone,enrollment_year,course_batch,city,graduation_year,...,critical_thinking,interpersonal_skills,placement_id,mock_interview_score,internships_completed,placement_status,company_name,placement_package,interview_rounds_cleared,placement_date
0,1,Matthew Hoover,27,Female,tylerjohnson@example.net,001-851-471-8702,2021,DS Batch 2,South Kimberlyview,2025,...,92,74,None,54,3,Not Ready,None,NaN,0,None
1,2,Michael Santos,23,Male,melissa86@example.com,+1-978-409-1343x1611,2020,DS Batch 4,Rebeccaton,2024,...,61,81,None,54,0,Ready,None,NaN,0,None
2,3,Anthony Howard,25,Female,hthomas@example.com,001-922-421-9693,2019,DS Batch 3,South Dana,2023,...,67,88,None,59,2,Ready,None,NaN,0,None
3,4,Michael Nolan,25,Other,rsantana@example.net,(617)559-4647,2023,DS Batch 4,Castanedaville,2027,...,83,62,None,65,0,Placed,Webster-Wolf,12.17,5,2025-05-28
4,5,Kenneth Andrews,28,Female,andrew64@example.org,001-509-674-3953,2019,DS Batch 1,Lake Colton,2023,...,81,85,None,88,1,Placed,"Glass, Cunningham and Reid",7.56,4,2025-08-04

In [33]:
print("Missing values per column:")
print(df_merged.isnull().sum())

Missing values per column:
student_id                   0
name                         0
age                          0
gender                       0
email                        0
phone                        0
enrollment_year              0
course_batch                 0
city                         0
graduation_year              0
programming_id              20
language                     0
problems_solved              0
assessments_completed        0
mini_projects                0
certifications_earned        0
latest_project_score         0
soft_skill_id               20
communication                0
teamwork                     0
presentation                 0
leadership                   0
critical_thinking            0
interpersonal_skills         0
placement_id                20
mock_interview_score         0
internships_completed        0
placement_status             0
company_name                13
placement_package           13
interview_rounds_cleared     0
placement_date              13
dtype: int64

In [34]:
df_merged.head()

,student_id,name,age,gender,email,phone,enrollment_year,course_batch,city,graduation_year,...,critical_thinking,interpersonal_skills,placement_id,mock_interview_score,internships_completed,placement_status,company_name,placement_package,interview_rounds_cleared,placement_date
0,1,Matthew Hoover,27,Female,tylerjohnson@example.net,001-851-471-8702,2021,DS Batch 2,South Kimberlyview,2025,...,92,74,None,54,3,Not Ready,None,NaN,0,None
1,2,Michael Santos,23,Male,melissa86@example.com,+1-978-409-1343x1611,2020,DS Batch 4,Rebeccaton,2024,...,61,81,None,54,0,Ready,None,NaN,0,None
2,3,Anthony Howard,25,Female,hthomas@example.com,001-922-421-9693,2019,DS Batch 3,South Dana,2023,...,67,88,None,59,2,Ready,None,NaN,0,None
3,4,Michael Nolan,25,Other,rsantana@example.net,(617)559-4647,2023,DS Batch 4,Castanedaville,2027,...,83,62,None,65,0,Placed,Webster-Wolf,12.17,5,2025-05-28
4,5,Kenneth Andrews,28,Female,andrew64@example.org,001-509-674-3953,2019,DS Batch 1,Lake Colton,2023,...,81,85,None,88,1,Placed,"Glass, Cunningham and Reid",7.56,4,2025-08-04

In [35]:
# ------------------------------
# Step 6: SQL Queries & Insights
# ------------------------------

# Import necessary libraries
import sqlite3
import pandas as pd
import warnings

# Suppress warnings for clean output
warnings.filterwarnings("ignore")

# Establish SQLite connection
conn = sqlite3.connect("placement_eligibility.db")
cursor = conn.cursor()
print("✅ Connected to SQLite Database")

✅ Connected to SQLite Database

In [36]:
def run_query(query, conn=conn):
    """Execute SQL query and return a pandas DataFrame"""
    df = pd.read_sql_query(query, conn)
    print(f"✅ Query executed: {query.split()[0]} ...")  
    return df

In [37]:
 # 3️⃣ Queries with Insights

In [38]:
# Query 1: Average Programming Performance per Batch

query1 = """
SELECT s.course_batch,
       ROUND(AVG(p.latest_project_score),2) AS avg_project_score,
       ROUND(AVG(p.problems_solved),2) AS avg_problems_solved
FROM Students s
LEFT JOIN Programming p ON s.student_id = p.student_id
GROUP BY s.course_batch
ORDER BY avg_project_score DESC
"""
avg_prog_batch = run_query(query1)
avg_prog_batch

✅ Query executed: SELECT ...

  course_batch  avg_project_score  avg_problems_solved
0   DS Batch 5              96.12                45.33
1   DS Batch 4              86.12                56.71
2   DS Batch 3              82.32                46.86
3   DS Batch 2              74.72                82.50
4   DS Batch 1              69.76                99.00

In [39]:
# Query 2: Top 5 Students by Programming Score

query2 = """
SELECT s.name, s.course_batch, p.latest_project_score, p.problems_solved
FROM Students s
JOIN Programming p ON s.student_id = p.student_id
ORDER BY p.latest_project_score DESC
LIMIT 5
"""
top_programmers = run_query(query2)
top_programmers

✅ Query executed: SELECT ...

               name course_batch  latest_project_score  problems_solved
0   Kristina Herman   DS Batch 4                 98.00               95
1     Donald Farmer   DS Batch 4                 97.71               83
2        Joe Miller   DS Batch 5                 96.28               31
3  Michelle Schmitt   DS Batch 5                 96.19               17
4     Patrick Moore   DS Batch 5                 95.89               88

In [40]:
# Query 3: Students Ready for Placement

query3 = """
SELECT s.name, s.course_batch, p.latest_project_score, pl.placement_status
FROM Students s
JOIN Programming p ON s.student_id = p.student_id
JOIN Placements pl ON s.student_id = pl.student_id
WHERE pl.placement_status = 'Ready'
ORDER BY p.latest_project_score DESC
"""
ready_students = run_query(query3)
ready_students

✅ Query executed: SELECT ...

             name course_batch  latest_project_score placement_status
0   Patrick Moore   DS Batch 5                 95.89            Ready
1  Michael Santos   DS Batch 4                 92.74            Ready
2      Anna Lewis   DS Batch 4                 90.63            Ready
3   Dan Dougherty   DS Batch 3                 73.45            Ready
4      Seth Reese   DS Batch 4                 67.27            Ready
5  Anthony Howard   DS Batch 3                 65.89            Ready

In [41]:
# Query 4: Top Soft Skills Students

query4 = """
SELECT s.name,
       (ss.communication + ss.teamwork + ss.presentation + ss.leadership + ss.critical_thinking + ss.interpersonal_skills)/6 AS avg_softskills
FROM Students s
JOIN SoftSkills ss ON s.student_id = ss.student_id
ORDER BY avg_softskills DESC
LIMIT 5
"""
top_softskills = run_query(query4)
top_softskills

✅ Query executed: SELECT ...

                name  avg_softskills
0      Amanda Kramer              87
1     Matthew Hoover              86
2  Christian Leblanc              85
3         Anna Lewis              82
4      Patrick Moore              80

In [42]:
# Query 5: Average Soft Skills per Batch

query5 = """
SELECT s.course_batch,
       ROUND(AVG(ss.communication),2) AS avg_communication,
       ROUND(AVG(ss.teamwork),2) AS avg_teamwork,
       ROUND(AVG(ss.presentation),2) AS avg_presentation,
       ROUND(AVG(ss.leadership),2) AS avg_leadership,
       ROUND(AVG(ss.critical_thinking),2) AS avg_critical_thinking,
       ROUND(AVG(ss.interpersonal_skills),2) AS avg_interpersonal_skills
FROM Students s
JOIN SoftSkills ss ON s.student_id = ss.student_id
GROUP BY s.course_batch
ORDER BY avg_communication DESC
"""
softskills_batch = run_query(query5)
softskills_batch

✅ Query executed: SELECT ...

,course_batch,avg_communication,avg_teamwork,avg_presentation,avg_leadership,avg_critical_thinking,avg_interpersonal_skills
0,DS Batch 2,88.50,73.00,77.50,77.50,78.00,65.50
1,DS Batch 3,83.86,69.29,75.57,72.57,83.14,81.57
2,DS Batch 4,75.86,70.00,81.00,60.43,73.57,76.86
3,DS Batch 5,75.00,75.67,68.00,75.67,77.00,71.33
4,DS Batch 1,55.00,65.00,96.00,76.00,81.00,85.00

In [43]:
# Query 6: Placement Status Distribution

query6 = """
SELECT placement_status, COUNT(*) AS student_count
FROM Placements
GROUP BY placement_status
"""
placement_counts = run_query(query6)
placement_counts

✅ Query executed: SELECT ...

  placement_status  student_count
0        Not Ready              7
1           Placed              7
2            Ready              6

In [44]:
# Query 7: Average Placement Package for Placed Students

query7 = """
SELECT ROUND(AVG(placement_package),2) AS avg_package
FROM Placements
WHERE placement_status = 'Placed'
"""
avg_package = run_query(query7)
avg_package

✅ Query executed: SELECT ...

   avg_package
0         9.98

In [45]:
# Query 8: High Programming Score but Not Placed

query8 = """
SELECT s.name, p.latest_project_score, pl.mock_interview_score, pl.placement_status
FROM Students s
JOIN Programming p ON s.student_id = p.student_id
JOIN Placements pl ON s.student_id = pl.student_id
WHERE p.latest_project_score > 85 AND pl.placement_status != 'Placed'
ORDER BY p.latest_project_score DESC
"""
high_prog_low_place = run_query(query8)
high_prog_low_place

✅ Query executed: SELECT ...

,name,latest_project_score,mock_interview_score,placement_status
0,Donald Farmer,97.71,100,Not Ready
1,Michelle Schmitt,96.19,93,Not Ready
2,Patrick Moore,95.89,60,Ready
3,Ashley Gordon,95.72,94,Not Ready
4,Michael Santos,92.74,54,Ready
5,Amanda Kramer,92.16,69,Not Ready
6,Anna Lewis,90.63,85,Ready
7,Michelle James,87.76,52,Not Ready
8,Matthew Hoover,86.35,54,Not Ready

In [46]:
# Query 9: Internship Count vs Placement Status

query9 = """
SELECT internships_completed, placement_status, COUNT(*) AS count
FROM Placements
GROUP BY internships_completed, placement_status
ORDER BY internships_completed DESC
"""
internship_vs_placement = run_query(query9)
internship_vs_placement

✅ Query executed: SELECT ...

   internships_completed placement_status  count
0                      3        Not Ready      4
1                      3            Ready      1
2                      2           Placed      2
3                      2            Ready      1
4                      1        Not Ready      3
5                      1           Placed      3
6                      1            Ready      1
7                      0           Placed      2
8                      0            Ready      3

In [47]:
# Query 10: Students Needing Soft Skills Improvement

query10 = """
SELECT s.name, ss.communication, ss.teamwork, ss.presentation, pl.placement_status
FROM Students s
JOIN SoftSkills ss ON s.student_id = ss.student_id
JOIN Placements pl ON s.student_id = pl.student_id
WHERE ss.communication < 60 OR ss.teamwork < 60 OR ss.presentation < 60
ORDER BY ss.communication ASC
"""
students_improve = run_query(query10)
students_improve

✅ Query executed: SELECT ...

               name  communication  teamwork  presentation placement_status
0        Joe Miller             50        86            68           Placed
1   Kenneth Andrews             55        65            96           Placed
2    Denise Stanley             58        67            52           Placed
3    Michael Santos             71        51            81            Ready
4        Seth Reese             71        61            53            Ready
5  Michelle Schmitt             88        68            56        Not Ready
6     Dan Dougherty             94        58            90            Ready